version: '3'

services: 

  nginx:
      build:
        context: nginx
      container_name: nginx
      networks:
       - node-network
      ports:
       - "8080:80"
      depends_on: 
       - app

  app:
    build: 
      context: node
    container_name: app
    networks: 
      - node-network
   # volumes: 
      #- ./node:/usr/src/app
      #- ./node/node_modules:/usr/src/app/node_modules
    tty: true
    ports:
       - "3000:3000"
    depends_on: 
       db:
        condition: service_healthy

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
      - "./bd-scripts/schema.sql:/docker-entrypoint-initdb.d/1.sql"
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            interval: 20s
            timeout: 30s
            retries: 5

networks: 
  node-network:
    driver: bridge    